Login flow with persistent redux storage
trinsic-id/sdk-examples pull request #20
Opened 2021-12-20 15:20 UTC by MichaelEdwardBlack

Adds the full login flow to the wallet sample app

2021-12-20 15:43 UTC, fundthmcalculus requested changes

2021-12-20 15:43 UTC, fundthmcalculus commented on browser/react-wallet/package.json
> +    "@trinsic/trinsic-web": "../../../sdk/web",
local path reference isn't portable?

2021-12-20 15:43 UTC, fundthmcalculus commented on browser/react-wallet/scratch.js
> +details.setEmail("michaelblack117@gmail.com");
personal email is a security issue. `hello@trinsic.id` would be better. Right @michaeldboyd ?
make sure to force-push to eliminate the history of this.

2021-12-20 15:43 UTC, fundthmcalculus commented on browser/react-wallet/src/actions/index.js
> +    // request.setName(auth.user.name);
not needed because SMS to verify email?

2021-12-20 15:43 UTC, fundthmcalculus commented on browser/react-wallet/src/pages/HomePage.js
> +        Hello World
😀

2021-12-20 16:32 UTC, tmarkovski commented on browser/react-wallet/package.json
> +    "@trinsic/trinsic": "^1.2.1",
This is a node package, it shouldn't be referenced

2021-12-28 15:28 UTC, lucasamonrc commented on browser/react-wallet/package.json
> +    "@trinsic/trinsic-web": "../../../sdk/web",
I am having problems with line 11 as well. I'm sure it's because I don't have the sdk in that particular path. Should it be that way though?

2021-12-28 15:30 UTC, lucasamonrc requested changes

2021-12-28 15:30 UTC, lucasamonrc commented on browser/react-wallet/package.json
> +    "@trinsic/trinsic-web": "../../../sdk/web",
I am having problems with line 11 as well. I'm sure it's because I don't have the sdk in that particular path. Should it be that way though?

2022-01-25 21:37 UTC, fundthmcalculus commented
@MichaelEdwardBlack thoughts on this?

2022-02-10 16:53 UTC, closed without merging